// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_startScreen;
extern lv_obj_t * ui_headingLbl;
extern lv_obj_t * ui_oilTempLbl;
extern lv_obj_t * ui_oilTempValueLbl;
extern lv_obj_t * ui_oilTempUnitLbl;
extern lv_obj_t * ui_rawCanMsgOilLbl;
extern lv_obj_t * ui_rawMsgValueOilLbl;
void ui_event_updateOilTempBtn(lv_event_t * e);
extern lv_obj_t * ui_updateOilTempBtn;
void ui_event_canMsgSendBtn(lv_event_t * e);
extern lv_obj_t * ui_canMsgSendBtn;
void ui_event_myCustomBtn(lv_event_t * e);
extern lv_obj_t * ui_myCustomBtn;
// CUSTOM VARIABLES
extern lv_obj_t * uic_startScreen;
extern lv_obj_t * uic_headingLbl;
extern lv_obj_t * uic_oilTempLbl;
extern lv_obj_t * uic_oilTempValueLbl;
extern lv_obj_t * uic_oilTempUnitLbl;
extern lv_obj_t * uic_rawCanMsgOilLbl;
extern lv_obj_t * uic_rawMsgValueOilLbl;
extern lv_obj_t * uic_updateOilTempBtn;
extern lv_obj_t * uic_canMsgSendBtn;
extern lv_obj_t * uic_myCustomBtn;

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
