// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_CONTAINER1_H
#define _UI_COMP_CONTAINER1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Container1
#define UI_COMP_CONTAINER1_CONTAINER1 0
#define _UI_COMP_CONTAINER1_NUM 1
lv_obj_t * ui_Container1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
