// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT Container1

lv_obj_t * ui_Container1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container1;
    cui_Container1 = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container1);
    lv_obj_set_width(cui_Container1, 3778);
    lv_obj_set_height(cui_Container1, 50);
    lv_obj_set_align(cui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER1_NUM);
    children[UI_COMP_CONTAINER1_CONTAINER1] = cui_Container1;
    lv_obj_add_event_cb(cui_Container1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container1_create_hook(cui_Container1);
    return cui_Container1;
}

