// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#include <Arduino.h>
#include "ui.h"
#include <WaveshareCAN.h>

extern WaveshareCAN can;

int sensor_value = 0;

void updateOilTemp(lv_event_t * e)
{
	// Your code here
  sensor_value += 1;
  char buffer[10];
  sprintf(buffer, "%d", sensor_value);
  lv_label_set_text(ui_oilTempValueLbl, buffer);
  Serial.println("Oil Temperature updated ...");
}

void sendCanMessage(lv_event_t * e)
{
// Your code here
  Serial.println("Sending CAN message: 0x 00, 01, 02, 03, 04, 05, 06, 07");
  uint8_t data[8] = { 00, 01, 02, 03, 04, 05, 06, 07 };
  can.sendMessage(0x123, data, 8);

  Serial.println("CAN message was sent ...");
}

void myCustomFunction(lv_event_t * e)
{
	// Your code here
  Serial.println("myCustomFunction - nothing special");
}
